# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 338)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.ob = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.ob.setMinimum(1)
        self.ob.setMaximum(1000000000)
        self.ob.setObjectName("ob")
        self.gridLayout.addWidget(self.ob, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.obz = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.obz.setObjectName("obz")
        self.obz.addItem("")
        self.obz.addItem("")
        self.obz.addItem("")
        self.gridLayout.addWidget(self.obz, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.molot = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.molot.setObjectName("molot")
        self.molot.addItem("")
        self.molot.addItem("")
        self.gridLayout.addWidget(self.molot, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.vkus = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.vkus.setObjectName("vkus")
        self.gridLayout.addWidget(self.vkus, 4, 1, 1, 1)
        self.price = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.price.setMinimum(1)
        self.price.setMaximum(1000000000)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 5, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.idd = QtWidgets.QLabel(self.gridLayoutWidget)
        self.idd.setObjectName("idd")
        self.gridLayout.addWidget(self.idd, 0, 1, 1, 1)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(10, 230, 411, 51))
        self.save.setObjectName("save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Цена"))
        self.label_6.setText(_translate("MainWindow", "Объём упаковки"))
        self.label_3.setText(_translate("MainWindow", "Молотый/В зёрнах"))
        self.obz.setItemText(0, _translate("MainWindow", "Слабая"))
        self.obz.setItemText(1, _translate("MainWindow", "Средняя"))
        self.obz.setItemText(2, _translate("MainWindow", "Сильная"))
        self.label.setText(_translate("MainWindow", "Название сорта"))
        self.molot.setItemText(0, _translate("MainWindow", "Молотый"))
        self.molot.setItemText(1, _translate("MainWindow", "В зёрнах"))
        self.label_2.setText(_translate("MainWindow", "Степень обжарки"))
        self.label_4.setText(_translate("MainWindow", "Описание вкуса"))
        self.label_7.setText(_translate("MainWindow", "id"))
        self.idd.setText(_translate("MainWindow", "1"))
        self.save.setText(_translate("MainWindow", "Сохранить"))

